"""add_admin_feedback_and_analytics_tables

Revision ID: 0948791d464b
Revises: e3f4a5b6c7d8
Create Date: 2026-08-16 22:46:29.128394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0948791d464b'
down_revision: Union[str, Sequence[str], None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenges_content_hash'), 'challenges', ['content_hash'], unique=False)
    op.drop_constraint(op.f('map_nodes_challenge_id_fkey'), 'map_nodes', type_='foreignkey')
    op.drop_column('map_nodes', 'boss_id')
    op.drop_column('map_nodes', 'challenge_id')
    op.drop_constraint(op.f('passkeys_credential_id_key'), 'passkeys', type_='unique')
    op.drop_index(op.f('ix_passkeys_credential_id'), table_name='passkeys')
    op.create_index(op.f('ix_passkeys_credential_id'), 'passkeys', ['credential_id'], unique=True)
    op.create_index(op.f('ix_question_sets_content_hash'), 'question_sets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_test_cases_challenge_id'), 'test_cases', ['challenge_id'], unique=False)
    op.create_unique_constraint('uq_user_node_assignment', 'user_node_assignments', ['user_id', 'node_id'])
    op.drop_constraint(op.f('user_sessions_refresh_token_hash_key'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_unique_constraint(op.f('user_sessions_refresh_token_hash_key'), 'user_sessions', ['refresh_token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_node_assignment', 'user_node_assignments', type_='unique')
    op.drop_index(op.f('ix_test_cases_challenge_id'), table_name='test_cases')
    op.drop_index(op.f('ix_question_sets_content_hash'), table_name='question_sets')
    op.drop_index(op.f('ix_passkeys_credential_id'), table_name='passkeys')
    op.create_index(op.f('ix_passkeys_credential_id'), 'passkeys', ['credential_id'], unique=False)
    op.create_unique_constraint(op.f('passkeys_credential_id_key'), 'passkeys', ['credential_id'], postgresql_nulls_not_distinct=False)
    op.add_column('map_nodes', sa.Column('challenge_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('map_nodes', sa.Column('boss_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('map_nodes_challenge_id_fkey'), 'map_nodes', 'challenges', ['challenge_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_challenges_content_hash'), table_name='challenges')
    # ### end Alembic commands ###
