"""add contest models

Revision ID: 1268ec569d5d
Revises: 8f35dd7f8a21
Create Date: 2026-08-11 22:46:02.121894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1268ec569d5d'
down_revision: Union[str, Sequence[str], None] = '8f35dd7f8a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_table('contest_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_participants_contest_id'), 'contest_participants', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_participants_user_id'), 'contest_participants', ['user_id'], unique=False)
    op.create_table('contest_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_solve_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_submissions_contest_id'), 'contest_submissions', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_submissions_user_id'), 'contest_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_submissions_user_id'), table_name='contest_submissions')
    op.drop_index(op.f('ix_contest_submissions_contest_id'), table_name='contest_submissions')
    op.drop_table('contest_submissions')
    op.drop_index(op.f('ix_contest_participants_user_id'), table_name='contest_participants')
    op.drop_index(op.f('ix_contest_participants_contest_id'), table_name='contest_participants')
    op.drop_table('contest_participants')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
