"""Add problem bank metadata to Challenge

Revision ID: 350ada93de22
Revises: f6fef5d1d916
Create Date: 2026-08-11 22:23:49.165085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350ada93de22'
down_revision: Union[str, Sequence[str], None] = 'f6fef5d1d916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('tags', sa.JSON(), nullable=False))
    op.add_column('challenges', sa.Column('canonical_solution', sa.Text(), nullable=True))
    op.add_column('challenges', sa.Column('hints', sa.JSON(), nullable=False))
    op.add_column('challenges', sa.Column('generated_by', sa.String(length=50), nullable=False))
    op.add_column('challenges', sa.Column('quality_score', sa.Float(), nullable=False))
    op.add_column('challenges', sa.Column('validation_status', sa.String(length=30), nullable=False))
    op.add_column('challenges', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.add_column('challenges', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'created_at')
    op.drop_column('challenges', 'usage_count')
    op.drop_column('challenges', 'validation_status')
    op.drop_column('challenges', 'quality_score')
    op.drop_column('challenges', 'generated_by')
    op.drop_column('challenges', 'hints')
    op.drop_column('challenges', 'canonical_solution')
    op.drop_column('challenges', 'tags')
    # ### end Alembic commands ###
