"""Add problem bank metadata to Challenge

Revision ID: 350ada93de22
Revises: f6fef5d1d916
Create Date: 2026-08-11 22:23:49.165085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350ada93de22'
down_revision: Union[str, Sequence[str], None] = 'f6fef5d1d916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: skips ADD COLUMN if the column already exists in the DB.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_cols = {col['name'] for col in inspector.get_columns('challenges')}

    new_columns = [
        ('tags',               sa.Column('tags', sa.JSON(), nullable=False)),
        ('canonical_solution', sa.Column('canonical_solution', sa.Text(), nullable=True)),
        ('hints',              sa.Column('hints', sa.JSON(), nullable=False)),
        ('generated_by',      sa.Column('generated_by', sa.String(length=50), nullable=False)),
        ('quality_score',     sa.Column('quality_score', sa.Float(), nullable=False)),
        ('validation_status', sa.Column('validation_status', sa.String(length=30), nullable=False)),
        ('usage_count',       sa.Column('usage_count', sa.Integer(), nullable=False)),
        ('created_at',        sa.Column('created_at', sa.DateTime(), nullable=False)),
    ]
    for col_name, col_def in new_columns:
        if col_name not in existing_cols:
            op.add_column('challenges', col_def)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'created_at')
    op.drop_column('challenges', 'usage_count')
    op.drop_column('challenges', 'validation_status')
    op.drop_column('challenges', 'quality_score')
    op.drop_column('challenges', 'generated_by')
    op.drop_column('challenges', 'hints')
    op.drop_column('challenges', 'canonical_solution')
    op.drop_column('challenges', 'tags')
    # ### end Alembic commands ###
