"""add mistake log

Revision ID: 69e702491500
Revises: dca4cae984b9
Create Date: 2026-08-11 22:36:57.539941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e702491500'
down_revision: Union[str, Sequence[str], None] = 'dca4cae984b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: skips CREATE TABLE / CREATE INDEX if they already exist.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'mistake_logs' not in existing_tables:
        op.create_table('mistake_logs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('challenge_id', sa.String(length=50), nullable=False),
        sa.Column('error_type', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('code_snapshot', sa.Text(), nullable=False),
        sa.Column('ai_analysis', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_mistake_logs_error_type'), 'mistake_logs', ['error_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_mistake_logs_id'), 'mistake_logs', ['id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_mistake_logs_user_id'), 'mistake_logs', ['user_id'], unique=False, if_not_exists=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistake_logs_user_id'), table_name='mistake_logs')
    op.drop_index(op.f('ix_mistake_logs_id'), table_name='mistake_logs')
    op.drop_index(op.f('ix_mistake_logs_error_type'), table_name='mistake_logs')
    op.drop_table('mistake_logs')
    # ### end Alembic commands ###
