"""add_completed_node_ids_and_node_stars_to_user_profiles

Revision ID: 7556e8d7de9e
Revises: 0948791d464b
Create Date: 2026-08-18 21:37:58.896941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7556e8d7de9e'
down_revision: Union[str, Sequence[str], None] = '0948791d464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('completed_node_ids', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('user_profiles', sa.Column('node_stars', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'node_stars')
    op.drop_column('user_profiles', 'completed_node_ids')
    # ### end Alembic commands ###
