"""add streak to profile

Revision ID: 8f35dd7f8a21
Revises: 69e702491500
Create Date: 2026-08-11 22:44:17.750363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f35dd7f8a21'
down_revision: Union[str, Sequence[str], None] = '69e702491500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('last_activity_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'last_activity_date')
    # ### end Alembic commands ###
