"""add gamification models

Revision ID: dca4cae984b9
Revises: 350ada93de22
Create Date: 2026-08-11 22:31:24.649822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca4cae984b9'
down_revision: Union[str, Sequence[str], None] = '350ada93de22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent: skips CREATE TABLE / CREATE INDEX if they already exist.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'achievements' not in existing_tables:
        op.create_table('achievements',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('icon_name', sa.String(length=50), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('xp_reward', sa.Integer(), nullable=True),
        sa.Column('coin_reward', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'rating_history' not in existing_tables:
        op.create_table('rating_history',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('domain_type', sa.String(length=50), nullable=False),
        sa.Column('domain_id', sa.String(length=50), nullable=True),
        sa.Column('old_rating', sa.Integer(), nullable=False),
        sa.Column('new_rating', sa.Integer(), nullable=False),
        sa.Column('change_reason', sa.String(length=100), nullable=False),
        sa.Column('challenge_id', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_rating_history_id'), 'rating_history', ['id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_rating_history_user_id'), 'rating_history', ['user_id'], unique=False, if_not_exists=True)

    if 'user_achievements' not in existing_tables:
        op.create_table('user_achievements',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('achievement_id', sa.String(length=50), nullable=False),
        sa.Column('unlocked_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False, if_not_exists=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_rating_history_user_id'), table_name='rating_history')
    op.drop_index(op.f('ix_rating_history_id'), table_name='rating_history')
    op.drop_table('rating_history')
    op.drop_table('achievements')
    # ### end Alembic commands ###
