"""Add learning models and remove skill_ratings

Revision ID: f6fef5d1d916
Revises: 
Create Date: 2026-08-11 22:17:37.254256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fef5d1d916'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_category'), 'topics', ['category'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('user_language_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_percentage', sa.Float(), nullable=False),
    sa.Column('skill_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_mastery_language_id'), 'user_language_mastery', ['language_id'], unique=False)
    op.create_index(op.f('ix_user_language_mastery_user_id'), 'user_language_mastery', ['user_id'], unique=False)
    op.create_table('user_topic_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_percentage', sa.Float(), nullable=False),
    sa.Column('skill_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_topic_mastery_topic_id'), 'user_topic_mastery', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_mastery_user_id'), 'user_topic_mastery', ['user_id'], unique=False)
    op.drop_table('skill_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_ratings',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('python', sa.INTEGER(), nullable=False),
    sa.Column('javascript', sa.INTEGER(), nullable=False),
    sa.Column('algorithms', sa.INTEGER(), nullable=False),
    sa.Column('debugging', sa.INTEGER(), nullable=False),
    sa.Column('databases', sa.INTEGER(), nullable=False),
    sa.Column('system_design', sa.INTEGER(), nullable=False),
    sa.Column('ai_engineering', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('ix_user_topic_mastery_user_id'), table_name='user_topic_mastery')
    op.drop_index(op.f('ix_user_topic_mastery_topic_id'), table_name='user_topic_mastery')
    op.drop_table('user_topic_mastery')
    op.drop_index(op.f('ix_user_language_mastery_user_id'), table_name='user_language_mastery')
    op.drop_index(op.f('ix_user_language_mastery_language_id'), table_name='user_language_mastery')
    op.drop_table('user_language_mastery')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index(op.f('ix_topics_category'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
